name: Deploy Streamlit App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test app can start
      run: |
        # Test that the app can be imported without errors
        python -c "import app; print('App imports successfully')"
        
    - name: Check model file exists
      run: |
        # Check if model file exists (optional since app handles missing model)
        if [ -f "generator_model.pth" ]; then
          echo "Model file found"
        else
          echo "Model file not found - app will use untrained model"
        fi

  # Uncomment below for Heroku deployment
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: akhileshns/heroku-deploy@v3.12.12
  #     with:
  #       heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #       heroku_app_name: "your-streamlit-app-name"
  #       heroku_email: "your-email@example.com"
